env:
  node: true
  es2020: true

ignorePatterns:
  - dist
  - examples

extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: [./tsconfig.json, ./tsconfig.dts.json]
    rules:
      "@typescript-eslint/restrict-template-expressions": off
